apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: update-nodes-clusterrole
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: update-nodes-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: update-nodes-clusterrole
subjects:
  - kind: ServiceAccount
    name: update-nodes-sa
    namespace: monitoring

